-- 코드를 입력하세요
SELECT FLAVOR FROM
    (SELECT SUM(TT) AS TTT, FLAVOR FROM 
        (SELECT SUM(TOTAL_ORDER) AS TT, FLAVOR FROM FIRST_HALF
        GROUP BY FLAVOR

        UNION ALL

        SELECT SUM(TOTAL_ORDER) AS TT, FLAVOR FROM JULY
        GROUP BY FLAVOR) AS T
    GROUP BY FLAVOR
    ORDER BY TTT DESC) AS TTTTT
    LIMIT 3;
 