-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM (SELECT B.ITEM_ID FROM ITEM_INFO A JOIN ITEM_TREE B ON B.PARENT_ITEM_ID = A.ITEM_ID
WHERE A.RARITY = 'RARE') AS T JOIN ITEM_INFO A ON T.ITEM_ID = A.ITEM_ID
ORDER BY ITEM_ID DESC
